# Generated by Django 4.1.6 on 2023-02-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_mydetail"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mydetail", old_name="education_details", new_name="description",
        ),
        migrations.RenameField(
            model_name="mydetail", old_name="name", new_name="full_name",
        ),
        migrations.RemoveField(model_name="mydetail", name="technical_skill",),
        migrations.RemoveField(model_name="mydetail", name="working_experience",),
        migrations.AddField(
            model_name="mydetail",
            name="current_company_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mydetail",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="mydetail",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="detail/"),
        ),
        migrations.AddField(
            model_name="mydetail",
            name="professional_title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mydetail",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="detail/cv/",
                verbose_name="Updated Resume",
            ),
        ),
    ]
