# Generated by Django 4.1.6 on 2023-02-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_blog_contact_experience_alter_mydetail_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="is_replied",
            field=models.BooleanField(default=False),
        ),
    ]
